server.port=8080
spring.application.name=pandaravazhi

spring.datasource.url=jdbc:mysql://localhost:3306/semippu
spring.datasource.username=pandaravazhi
spring.datasource.password=pandaramachari
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
